services:
  tests:
    build: .
    volumes:
      - ./allure-results:/framework/allure-results
    command: --env=${ENV:-dev}
    environment:
      AUTHORIZATION: ${AUTHORIZATION}
      BOOKER_USERNAME: ${BOOKER_USERNAME}
      BOOKER_PASSWORD: ${BOOKER_PASSWORD}
